name: docker-pipeline

on:
  push:
    branches: [main]

jobs:
  build-project:
    runs-on: self-hosted
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Install NPM dependencies
        run: npm install
      - name: Build and Export
        run: npm run generate
