name: docker-pipeline

on:
  push:
    branches: [main]

jobs:
  build-project:
    runs-on: actions/checkout@v2
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Install NPM dependencies
        run: npm install
      - name: Build 
        run: npm run build


