name: docker-pipeline

on:
  push:
    branches: [main]

jobs:
  build-project:
    runs-on: self-hosted
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Install NPM dependencies
        run: npm install
      - name: Build and Export
        run: npm run generate

  docker-build-push:
    needs: build-project
    name: Build docker
    runs-on: self-hosted
    # steps:
    #   - name: Checkout Code
    #     uses: actions/checkout@v2
    #   - name: Login to docker hub
    #     uses: docker/login-action@v2
    #     with:
    #       username: ${{ secrets.DOCKER_HUB_USERNAME }}
    #       password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
    #   - name: Set up Docker Buildx
    #     uses: docker/setup-buildx-action@v2
    #   - name: Build and push
    #     uses: docker/build-push-action@v3
    #     with:
    #       context: .
    #       file: ./Dockerfile
    #       push: true
    #       tags: ${{ secrets.DOCKER_HUB_USERNAME }}/docker-sample:0.1
    #       dockerfile: Dockerfile
    #       build-args: |
    #         --config=/C:\Users\Anmol\.docker\daemon.json
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Set up Docker Buildx
        run: docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
      - name: Build and push
        run: docker buildx build --file ./Dockerfile --tag ${{ secrets.DOCKER_HUB_USERNAME }}/docker-sample:0.1 --platform linux/amd64,linux/arm64 --push .
